/* ============================================================
   DataFrame - curriculum data
   PHASES (constellations) + STARS (lessons & projects).
   Each star provides the fields that get merged into the
   standard professor template (see template.js).
   ============================================================ */
window.DF = window.DF || {};

DF.LEVEL = "I am a Computer Science graduate: a strong programmer, comfortable in Python, but new to SQL and to the data-engineering field. Lean on my CS background; go fast on programming fundamentals, and be thorough on data-specific ideas.";

/* Laid out bottom-to-top: Launchpad is the base of the tree, the Capstone is the crown.
   Lower phases sit at larger y (screen bottom); later phases climb upward. */
DF.PHASES = {
  launch: { name: "Launchpad", order: 0, center: { x: 1350, y: 3720 } },
  ai:     { name: "AI-Assisted Engineering", order: 1, center: { x: 1350, y: 3340 } },
  sql:    { name: "SQL & Data Modeling", order: 2, center: { x: 1350, y: 2960 } },
  py:     { name: "Python for Data Engineering", order: 3, center: { x: 1350, y: 2580 } },
  wh:     { name: "Warehouse & Analytics Engineering", order: 4, center: { x: 1350, y: 2200 } },
  orch:   { name: "Orchestration & DataOps", order: 5, center: { x: 1350, y: 1820 } },
  cloud:  { name: "AWS Cloud & Lakehouse", order: 6, center: { x: 1350, y: 1440 } },
  stream: { name: "Big Data & Streaming", order: 7, center: { x: 1350, y: 1060 } },
  llm:    { name: "AI & LLM Engineering", order: 8, center: { x: 1350, y: 680 } },
  cap:    { name: "Capstone & Getting Hired", order: 9, center: { x: 1350, y: 300 } }
};

DF.STARS = [
  /* ---------- 0 · Launchpad ---------- */
  { id:"intro", phase:"launch", title:"How DataFrame Works", kind:"orientation", off:[-120,-40], prereq:[], est:"30 min",
    goal:"How to learn with an AI professor: the prompt-launcher flow, driving the AI, and tracking progress.",
    obj:["Understand the loop: open a star, hand the prompt to your AI, learn, meet the definition-of-done, mark it complete.",
         "Set expectations: you build real things and a real portfolio, not just watch lessons.",
         "Learn to push the AI to teach, quiz, and code-review you rather than hand you answers."],
    ai:{ t:"Meet your professor", p:"Every star assembles a full teaching prompt for Claude, ChatGPT, or Claude Code. You paste it in and the model runs the lesson.",
         v:"Verify you are learning, not just reading: at each step, predict outputs and explain ideas back before moving on." },
    body:"Explain how to get the most from an AI professor: ask it to go step by step, quiz me, and review my code like a senior engineer. Show me how to say \"do not give me the answer yet, make me try first.\" Then have me pick a star and start.",
    dod:[["I understand the star -> prompt -> learn -> complete loop",null],["I know how to push the AI to teach rather than spoon-feed",null]],
    res:[["Claude","docs","https://claude.ai/new"],["ChatGPT","docs","https://chatgpt.com/"]],
    iq:["What is the difference between a data engineer, analytics engineer, and ML engineer?"] },

  { id:"workstation", phase:"launch", title:"Your Engineer's Workstation", kind:"lesson", off:[10,60], prereq:["intro"], est:"3-4 hrs",
    goal:"Set up a professional local environment: Python (uv), VS Code, Git and GitHub, Docker, and an AI coding setup.",
    obj:["Install and configure uv, VS Code, Git, GitHub, and Docker Desktop.",
         "Create a reusable data-project template with sensible structure, .gitignore, and pre-commit.",
         "Configure your AI coding tools with project context files."],
    ai:{ t:"Configure your agents", p:"Set up Claude Code / Codex with a project context file so your agent understands each repo it works in.",
         v:"Verify the setup by having the agent run your test suite and read your README back to you accurately." },
    body:"Walk me through a clean 2026 Python setup with uv (not raw pip), a good VS Code config, Git and a GitHub account, and Docker Desktop. Help me build a reusable project template repository I will clone for every future project, including a README skeleton, .gitignore, pre-commit, and a tests folder.",
    dod:[["uv, VS Code, Git, GitHub, Docker all working",null],["A reusable project template repo on my GitHub","std"],["Pre-commit and a passing sample test configured","std"]],
    res:[["uv","docs","https://docs.astral.sh/uv/"],["Docker get started","docs","https://docs.docker.com/get-started/"],["pre-commit","docs","https://pre-commit.com/"]],
    iq:["Why use containers for data work instead of installing everything on your host?"] },

  { id:"de-map", phase:"launch", title:"How Data Engineering Works", kind:"lesson", off:[150,-30], prereq:["workstation"], est:"2-3 hrs",
    goal:"The mental map of the whole field: sources, ingestion, storage, transform, serve, orchestrate, observe.",
    obj:["Draw the end-to-end data pipeline and name the role of each stage.",
         "Distinguish lake vs warehouse vs lakehouse, and ETL vs ELT.",
         "See where DE, analytics engineering, ML engineering, and AI engineering meet and differ."],
    ai:{ t:"Diagram from a description", p:"Ask an agent to turn a described pipeline into a diagram (Mermaid), then critique whether the stages and arrows are right.",
         v:"Verify the diagram against reality by tracing one real dataset through every box yourself." },
    body:"Give me the big picture of modern data engineering: the flow from sources to serving, batch vs streaming, ETL vs ELT, and the lake / warehouse / lakehouse distinction. Use analogies to software architecture I already know. End with a Mermaid diagram of a reference pipeline I can reuse mentally throughout the course.",
    dod:[["I can draw and explain the reference pipeline",null],["I can define lake, warehouse, and lakehouse",null]],
    res:[["The Data Engineering Cookbook","article","https://github.com/andkret/Cookbook"],["Mermaid diagrams","docs","https://mermaid.js.org/"]],
    iq:["Explain ELT vs ETL and why ELT became dominant.","When would you choose a lakehouse over a warehouse?"] },

  /* ---------- 1 · AI-Assisted Engineering ---------- */
  { id:"context-eng", phase:"ai", title:"Context Engineering", kind:"lesson", off:[-160,20], prereq:["de-map"], est:"3-4 hrs", badges:["ai","emerging"],
    goal:"Curate what an agent sees: repo grounding, context files, doc retrieval, and avoiding context rot.",
    obj:["Distinguish context engineering (agent-to-LLM) from prompt engineering (human-to-LLM).",
         "Build reusable project context files and know what belongs in them.",
         "Recognize context rot and design workflows that avoid it."],
    ai:{ t:"This lesson is the AI skill", p:"You already use these tools; here you learn the discipline that separates power users: engineering the context window so the agent has exactly what it needs and nothing that poisons it.",
         v:"Verify by measuring: run the same task with thin vs. engineered context and compare output quality." },
    body:"Teach me context engineering as a real discipline. Cover project context files, grounding an agent in a repo, retrieving the right docs, and how context windows degrade. Give me a repeatable checklist. Then run an experiment: one real task done with lazy context, one with engineered context, and have me explain the difference.",
    dod:[["Wrote a reusable project context file","std"],["Ran the thin-vs-engineered context experiment",null],["Can define context vs prompt engineering",null]],
    res:[["Context engineering","article","https://www.philschmid.de/context-engineering"],["Claude Code best practices","docs","https://docs.anthropic.com/en/docs/claude-code"]],
    iq:["What is context rot and how do you mitigate it?","What belongs in a project context file vs. a one-off prompt?"] },

  { id:"spec-driven", phase:"ai", title:"Spec-Driven Development", kind:"lesson", off:[-40,-120], prereq:["context-eng"], est:"3-4 hrs", badges:["ai","emerging"],
    goal:"Use specs as the source of truth agents build from; issue-driven workflows with acceptance criteria.",
    obj:["Write a clear spec an agent can implement against.",
         "Run an issue-driven loop: spec, implement, review, iterate.",
         "Know when spec-driven helps and when it is overhead."],
    ai:{ t:"Specs as the contract", p:"The 2026 stack is specs plus context plus agents. A good spec makes agent output reviewable and correct instead of a guessing game.",
         v:"Verify: check the agent's output against every acceptance criterion in the spec, not against your vibe." },
    body:"Teach me spec-driven development: writing a spec with acceptance criteria, handing it to an agent, and reviewing against the spec. Have me take a small real feature, write the spec, let the agent implement it, and review the result line by line against the criteria.",
    dod:[["Wrote a spec with clear acceptance criteria","std"],["Implemented it via an agent and reviewed against the spec",null]],
    res:[["Spec-driven development","article","https://github.blog/developer-skills/agentic-ai-mcp-and-spec-driven-development-top-blog-posts-of-2025/"]],
    iq:["Why does a written spec improve agent output?","When is spec-driven development not worth the overhead?"] },

  { id:"mcp-agents", phase:"ai", title:"MCP & Tool-Augmented Agents", kind:"lesson", off:[70,-20], prereq:["context-eng"], est:"3-4 hrs", badges:["ai","emerging"],
    goal:"The Model Context Protocol: wiring agents to live tools and data, with allowlists and governance.",
    obj:["Explain what MCP is and why it matters for connecting agents to systems.",
         "Connect an agent to an MCP server and use its tools.",
         "Understand server allowlists and the security model."],
    ai:{ t:"Give the agent real tools", p:"MCP lets an agent read your data and call your tools instead of reasoning from static text. It is how agents stop being chatbots and start being operators.",
         v:"Verify tool calls: log what the agent actually invoked and confirm each call did what you expected." },
    body:"Teach me MCP end to end: the protocol, connecting an agent to an existing MCP server, and the governance model (allowlists, least privilege). Keep it concrete: wire up one server and have the agent use its tools on a real task. Note that I will build my own MCP server later in the AI & LLM track.",
    dod:[["Connected an agent to an MCP server and used its tools",null],["Can explain MCP and its security model",null]],
    res:[["Model Context Protocol","docs","https://modelcontextprotocol.io/"]],
    iq:["What problem does MCP solve that plain prompting does not?","How do you keep an MCP-connected agent from doing something dangerous?"] },

  { id:"skills-agents", phase:"ai", title:"Skills, Subagents & Orchestration", kind:"lesson", off:[190,-110], prereq:["mcp-agents"], est:"2-3 hrs", badges:["ai"],
    goal:"Reusable skills, splitting work across subagents, and when multi-agent helps vs hurts.",
    obj:["Package a reusable skill your agent can invoke repeatedly.",
         "Split a larger task across parallel or specialized subagents.",
         "Judge when orchestration adds value vs unnecessary complexity."],
    ai:{ t:"Compose agents", p:"Senior AI users build reusable skills and orchestrate subagents for big tasks, instead of one giant prompt that drifts.",
         v:"Verify each subagent's output independently before composing; a bad intermediate result poisons the whole chain." },
    body:"Teach me to build reusable skills and to orchestrate subagents. Have me take a multi-part task, decompose it, assign parts to subagents, and combine the results, then reflect on whether the orchestration actually beat a single well-scoped agent.",
    dod:[["Built one reusable skill",null],["Orchestrated a multi-step task across subagents",null]],
    res:[["Building effective agents","article","https://www.anthropic.com/engineering/building-effective-agents"]],
    iq:["When does multi-agent orchestration hurt more than help?"] },

  { id:"eval-ai", phase:"ai", title:"Evaluating & Trusting AI Output", kind:"lesson", off:[60,110], prereq:["spec-driven"], est:"2-3 hrs", badges:["ai","standards"],
    goal:"Verification workflows and quick evals for AI-generated code and data. Trust, then verify.",
    obj:["Build verification habits: run it, diff it, test it, read the plan or logs.",
         "Write a quick eval to check AI-generated code or data at scale.",
         "Internalize trust-then-verify as a permanent working habit."],
    ai:{ t:"Never ship unverified AI output", p:"The engineer who multiplies output with AI and can prove it is correct is far more valuable than one who cannot work without it, or one who ships hallucinations.",
         v:"Verify is the whole lesson: build a repeatable check for every kind of AI output you rely on." },
    body:"Teach me to verify AI output systematically. For code: tests, diffs, running it, reading the diff critically. For data: spot checks, row counts, schema checks, small evals. Have me set up a lightweight eval for an AI-generated artifact and make it fail on a planted error.",
    dod:[["Built a repeatable verification workflow","std"],["Wrote a quick eval that catches a planted error",null]],
    res:[["Your eval is the product","article","https://hamel.dev/blog/posts/evals/"]],
    iq:["How would you catch a subtle hallucination in AI-generated SQL?"] },

  { id:"m0", phase:"ai", title:"Milestone 0 · Automate a Real Chore", kind:"project", off:[210,90], prereq:["skills-agents","eval-ai"], est:"6-10 hrs", badges:["ai"],
    goal:"Build a small agentic workflow you will actually reuse, shipped as a clean, standalone repo.",
    obj:["Ship a working automation you personally use.",
         "Make the AI reliable with context engineering, specs, and verification.",
         "Package it as a production-ready, portfolio-worthy repository."],
    ai:{ t:"Your first AI-native tool", p:"Apply everything: context files, a spec, tool use, and an eval that keeps the automation honest over time.",
         v:"Verify: the automation runs unattended and your eval flags bad runs before you ship them." },
    body:"Coach me to build a small but genuinely useful agentic automation, from a spec through to a clean repo. Enforce the portfolio-repo rules the whole way. Help me choose one of the project options and scope it to something I will actually use.",
    dod:[["Working automation I actually use",null],["Reliability handled with context/spec/eval","std"],["Standalone repo: README, atomic commits, LICENSE, no AI/course references","std"]],
    res:[["Conventional Commits","docs","https://www.conventionalcommits.org/"]],
    iq:["How did you make a non-deterministic tool reliable enough to trust?"],
    options:[
      { th:"productivity", tt:"Inbox / notes digestor", p:"An agent that turns a messy feed (email export, notes, saved links) into a daily briefing you read every morning." },
      { th:"cs / automation", tt:"Project scaffolder", p:"A tool that scaffolds a new repo from your template with README, CI, and tests wired up from a one-line description." },
      { th:"finance", tt:"Statement categorizer", p:"An agent that categorizes and summarizes your bank/transaction exports, with an eval that checks its labels." } ] },

  /* ---------- 2 · SQL & Data Modeling ---------- */
  { id:"sql1", phase:"sql", title:"SQL I · Query Foundations", kind:"lesson", off:[-230,-40], prereq:["de-map"], est:"4-5 hrs", badges:["standards"],
    goal:"SELECT, WHERE, ORDER BY, DISTINCT, and set-based thinking vs the loops you reach for in Python.",
    obj:["Explain why SQL is declarative and set-based, and why that matters for data work.",
         "Write confident SELECT / WHERE / ORDER BY / DISTINCT queries against real data.",
         "Read a query plan at a high level and know why filtering early matters."],
    ai:{ t:"Text-to-SQL, done right", p:"A senior engineer uses an agent to draft SQL from a plain-English question and to explain an unfamiliar query plan, but never ships it blind.",
         v:"Verify with EXPLAIN, and check row counts against a known total before trusting an AI-written query." },
    body:"Use local PostgreSQL 16 in Docker so I learn the real thing. Give me the exact docker run and a fun seed dataset; offer me a choice of a personal-finance, listening-history, or transit-events table. Make me predict each query's output before running it. Introduce EXPLAIN gently. End with five queries I write unaided.",
    dod:[["Postgres running in Docker; dataset loaded",null],["I can explain declarative and set-based in my own words",null],["Wrote 5 correct queries from scratch",null],["Ran EXPLAIN once and understand early filtering",null],["Work committed to Git with clear messages","std"]],
    res:[["PostgreSQL Tutorial","docs","https://www.postgresql.org/docs/current/tutorial.html"],["Mode SQL Tutorial","article","https://mode.com/sql-tutorial/"]],
    iq:["What is the difference between WHERE and HAVING?","Why are two NULLs not considered equal?"] },

  { id:"sql2", phase:"sql", title:"SQL II · Joins & Aggregation", kind:"lesson", off:[-120,-120], prereq:["sql1"], est:"4-5 hrs",
    goal:"All join types, GROUP BY, HAVING, aggregate functions, and NULL semantics.",
    obj:["Use inner, left, right, full, and cross joins correctly and explain each.",
         "Aggregate with GROUP BY and HAVING, and reason about NULLs.",
         "Spot and avoid the fan-out trap when joining then aggregating."],
    ai:{ t:"Explain-my-join", p:"Have an agent explain why a join produced too many rows, then propose a fix, while you keep ownership of the reasoning.",
         v:"Verify row counts before and after every join; fan-out bugs hide in inflated totals." },
    body:"Teach joins and aggregation on the dataset from SQL I. Make me predict result-set sizes. Show me the classic fan-out bug (join then SUM) and how to catch it. End with a few multi-join analytical questions I answer unaided.",
    dod:[["Used every join type correctly",null],["Explained a fan-out bug and fixed it",null],["Answered 3 multi-join questions unaided",null]],
    res:[["Joins visualized","article","https://joins.spathon.com/"]],
    iq:["Explain a LEFT JOIN that returns unexpected NULLs.","How do you detect a fan-out before it corrupts a SUM?"] },

  { id:"sql3", phase:"sql", title:"SQL III · Advanced", kind:"lesson", off:[-30,-10], prereq:["sql2"], est:"5-6 hrs",
    goal:"Window functions, CTEs, subqueries, and set operations - the interview favorites.",
    obj:["Use window functions (ROW_NUMBER, RANK, LAG/LEAD, running totals).",
         "Structure complex logic with CTEs instead of nested subqueries.",
         "Combine result sets with UNION, INTERSECT, EXCEPT."],
    ai:{ t:"Refactor to readable SQL", p:"Ask an agent to refactor a gnarly nested query into CTEs, then defend or reject each change.",
         v:"Verify the refactor is equivalent: same row count and a diff of results on real data." },
    body:"Teach window functions, CTEs, subqueries, and set ops with practical examples: running totals, top-N-per-group, deduplication, month-over-month change. These are heavily tested in interviews, so drill me with real questions and review my answers like an interviewer.",
    dod:[["Solved top-N-per-group with a window function",null],["Refactored a nested query into CTEs",null],["Computed a running total and a month-over-month change",null]],
    res:[["Window functions (PostgreSQL)","docs","https://www.postgresql.org/docs/current/tutorial-window.html"]],
    iq:["When do you use a window function instead of GROUP BY?","Solve top-N per group two different ways."] },

  { id:"sql4", phase:"sql", title:"SQL IV · Performance", kind:"lesson", off:[80,-110], prereq:["sql3"], est:"3-4 hrs",
    goal:"Indexes, EXPLAIN ANALYZE, how the planner thinks, and avoiding full scans and N+1.",
    obj:["Read EXPLAIN ANALYZE and identify the expensive step.",
         "Choose useful indexes and know their cost.",
         "Recognize and fix full scans, N+1 patterns, and bad join orders."],
    ai:{ t:"Plan whisperer", p:"An agent can interpret a query plan and suggest an index, but the decision to add one is yours - indexes are not free.",
         v:"Verify the fix by re-running EXPLAIN ANALYZE and comparing actual time, not just the estimate." },
    body:"Teach query performance on a table with enough rows to matter. Show me how to read EXPLAIN ANALYZE, add an index and measure the improvement, and identify anti-patterns. Make me optimize a slow query and prove the speedup with numbers.",
    dod:[["Read EXPLAIN ANALYZE and found the bottleneck",null],["Added an index and measured the speedup",null]],
    res:[["Use the index, Luke","article","https://use-the-index-luke.com/"]],
    iq:["When can an index make a query slower?","How do you find the slowest part of a query?"] },

  { id:"duckdb", phase:"sql", title:"DuckDB", kind:"lesson", off:[70,90], prereq:["sql2"], est:"2-3 hrs", badges:["emerging"],
    goal:"The in-process OLAP engine: query Parquet/CSV/JSON from your laptop at warehouse speed.",
    obj:["Query large local files directly, with no server.",
         "Understand the small-data renaissance and when DuckDB replaces a whole pipeline.",
         "Use DuckDB as a local dev engine for the SQL you will run in the cloud."],
    ai:{ t:"Instant local analytics", p:"Point an agent at a folder of Parquet and have it profile the data and draft DuckDB queries - an analytics loop with zero infrastructure.",
         v:"Verify by re-running: DuckDB answers in milliseconds, so check every AI query yourself." },
    body:"Teach me why DuckDB is everywhere in 2026. Have me query a Parquet file of a million-plus rows in under a second, join across files, and call DuckDB from Python. Discuss honestly when DuckDB replaces a warehouse-plus-pipeline and when it does not.",
    dod:[["Queried a 1M+ row Parquet file locally under 1s",null],["Explained DuckDB vs a cloud warehouse tradeoff",null],["Used DuckDB from Python",null]],
    res:[["DuckDB docs","docs","https://duckdb.org/docs/"],["Awesome DuckDB","repo","https://github.com/davidgasquez/awesome-duckdb"]],
    iq:["When would you pick DuckDB over Snowflake?","How does an in-process engine differ from client-server?"] },

  { id:"relational", phase:"sql", title:"Relational Modeling", kind:"lesson", off:[-140,60], prereq:["sql1"], est:"3-4 hrs",
    goal:"Normalization, keys, ERDs, and OLTP vs OLAP.",
    obj:["Normalize a schema and know when to denormalize.",
         "Choose primary and foreign keys and draw an ERD.",
         "Contrast OLTP and OLAP workloads and their schema shapes."],
    ai:{ t:"Schema reviewer", p:"Have an agent critique your schema for normalization issues and missing keys; you make the final calls and defend them.",
         v:"Verify by loading data and checking that constraints actually hold." },
    body:"Teach relational modeling by having me design a normalized schema for a domain I care about, draw the ERD, and reason about keys and constraints. Contrast OLTP and OLAP so I understand why analytics schemas look different.",
    dod:[["Designed a normalized schema with an ERD",null],["Explained OLTP vs OLAP",null]],
    res:[["Database normalization","article","https://en.wikipedia.org/wiki/Database_normalization"],["dbdiagram.io","docs","https://dbdiagram.io/"]],
    iq:["When would you deliberately denormalize?","What is a natural vs surrogate key?"] },

  { id:"dimensional", phase:"sql", title:"Dimensional Modeling", kind:"lesson", off:[190,20], prereq:["relational","sql3"], est:"3-4 hrs",
    goal:"Kimball star schemas, facts and dimensions, and slowly changing dimensions.",
    obj:["Design a star schema with fact and dimension tables.",
         "Choose grain and additive vs non-additive measures.",
         "Handle slowly changing dimensions (type 1 and type 2)."],
    ai:{ t:"Model from questions", p:"Describe the business questions to an agent and have it propose a star schema; then you refine grain and SCD strategy.",
         v:"Verify the model answers the real questions by writing the queries against it." },
    body:"Teach Kimball dimensional modeling: facts, dimensions, grain, and slowly changing dimensions. Have me convert a normalized schema from the previous star into a star schema and explain the tradeoffs. This underpins the warehouse work coming next.",
    dod:[["Designed a star schema with correct grain",null],["Implemented a type-2 slowly changing dimension",null]],
    res:[["Kimball dimensional modeling","article","https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/dimensional-modeling-techniques/"]],
    iq:["Explain grain and why it matters.","Type 1 vs type 2 slowly changing dimension?"] },

  { id:"m1", phase:"sql", title:"Milestone 1 · Model Your World", kind:"project", off:[240,120], prereq:["sql4","dimensional","duckdb"], est:"10-14 hrs", badges:["standards"],
    goal:"Design and load a normalized Postgres database and answer 15 real business questions with SQL.",
    obj:["Design and load a normalized schema from a domain you care about.",
         "Answer 15 real business questions in SQL; validate a few in DuckDB.",
         "Ship a portfolio-ready repo: README, ERD, clean commit history."],
    ai:{ t:"AI as your reviewer", p:"Use an agent to critique your schema and draft candidate queries; you own every design decision and defend it.",
         v:"Verify every AI-suggested query with EXPLAIN and against known totals." },
    body:"Coach me through a portfolio project: pick a theme, design a normalized schema, load it into Postgres, answer 15 business questions in SQL, and validate some in DuckDB. Enforce the portfolio-repo rules from the first commit: README with an ERD and results, atomic conventional commits, a branching strategy, LICENSE, .gitignore. No emojis, and no mention of any AI tool or of this course anywhere in the repo.",
    dod:[["Normalized schema designed and ERD drawn",null],["15 business questions answered in SQL",null],["A few validated in DuckDB",null],["Atomic conventional commits and a branching strategy","std"],["README with architecture, results, LICENSE; no AI/course references","std"]],
    res:[["dbdiagram.io","docs","https://dbdiagram.io/"],["Conventional Commits","docs","https://www.conventionalcommits.org/"]],
    iq:["Walk me through your schema and one tradeoff you made.","How would this model change at 100x the data?"],
    options:[
      { th:"finance", tt:"Personal Finance Ledger", p:"Model accounts, transactions, and categories. Answer: where does my money actually go each month?" },
      { th:"media", tt:"Your Media Library", p:"Model your listening, film, or game history. Answer: what are my patterns over time?" },
      { th:"transit", tt:"City Transport Explorer", p:"Model a public-transit or traffic open dataset. Answer: where and when does the city jam up?" } ] },

  /* ---------- 3 · Python for Data Engineering ---------- */
  { id:"wrangling", phase:"py", title:"Data Wrangling: pandas & Polars", kind:"lesson", off:[-150,-70], prereq:["de-map"], est:"4-5 hrs", badges:["emerging"],
    goal:"Reshape and clean data with pandas and Polars, and know when each wins.",
    obj:["Do the core wrangling operations: filter, group, join, pivot, window.",
         "Use Polars for speed and lazy evaluation; know when pandas is fine.",
         "Handle missing data, types, and dates without silent corruption."],
    ai:{ t:"pandas-to-Polars", p:"Have an agent translate pandas to idiomatic Polars, then benchmark both so you learn the differences, not just the syntax.",
         v:"Verify the two produce identical results on real data before trusting the translation." },
    body:"Teach data wrangling in both pandas and Polars on a messy real dataset. Emphasize Polars as the fast modern default and its lazy API. Cover the traps: dtypes, missing values, timezones. Have me solve the same task in both and compare.",
    dod:[["Cleaned a messy dataset end to end",null],["Solved a task in both pandas and Polars",null]],
    res:[["Polars","docs","https://docs.pola.rs/"],["pandas","docs","https://pandas.pydata.org/docs/"]],
    iq:["Why is Polars faster than pandas for many workloads?","What is lazy evaluation and why does it help?"] },

  { id:"apis", phase:"py", title:"APIs & Web Data", kind:"lesson", off:[-30,-140], prereq:["wrangling"], est:"3-4 hrs",
    goal:"Pull data from live APIs: auth, pagination, rate limits, retries, and incremental extraction.",
    obj:["Authenticate and paginate through a real API.",
         "Handle rate limits with backoff and retries.",
         "Extract incrementally instead of re-pulling everything."],
    ai:{ t:"Reverse-engineer an API", p:"Use an agent to read API docs and draft a client, then harden it for the failure modes docs never mention.",
         v:"Verify against the live API with small requests and log every response before scaling up." },
    body:"Teach me to pull data from a live API reliably: auth, pagination, rate limits, exponential backoff, and incremental extraction with a cursor or timestamp. Have me build a small, resilient client for a real public API of my choice.",
    dod:[["Paginated and authenticated against a real API",null],["Implemented backoff and incremental extraction",null]],
    res:[["HTTPX","docs","https://www.python-httpx.org/"],["tenacity (retries)","docs","https://tenacity.readthedocs.io/"]],
    iq:["How do you extract incrementally from an API?","How should a client behave under rate limiting?"] },

  { id:"formats", phase:"py", title:"File Formats & Arrow", kind:"lesson", off:[-60,40], prereq:["wrangling"], est:"2-3 hrs",
    goal:"CSV, JSON, Parquet, Avro, and Arrow: columnar vs row, compression, and why Parquet is everywhere.",
    obj:["Choose the right format for a job and explain the tradeoffs.",
         "Explain columnar vs row storage and Arrow's role.",
         "Use partitioning and compression sensibly."],
    ai:{ t:"Format advisor", p:"Ask an agent to justify a format choice for a scenario, then poke holes in its reasoning.",
         v:"Verify by measuring file size and read speed for the same data across formats." },
    body:"Teach file formats and serialization: why Parquet dominates analytics, how columnar storage and Arrow work, and when Avro or JSON make sense. Have me convert a dataset across formats and measure size and read performance.",
    dod:[["Converted data across CSV, JSON, and Parquet",null],["Explained columnar vs row storage",null]],
    res:[["Apache Parquet","docs","https://parquet.apache.org/docs/"],["Apache Arrow","docs","https://arrow.apache.org/overview/"]],
    iq:["Why is Parquet good for analytics but bad for row-by-row writes?"] },

  { id:"dlt", phase:"py", title:"dlt · Modern Ingestion", kind:"lesson", off:[90,-60], prereq:["apis","formats"], est:"3-4 hrs", badges:["emerging"],
    goal:"Declarative Python-native pipelines with automatic schema evolution and incremental loading.",
    obj:["Build a source-to-destination pipeline with dlt.",
         "Use automatic schema inference and evolution.",
         "Load incrementally and idempotently."],
    ai:{ t:"Generate a source", p:"Use an agent to scaffold a dlt source from API docs, then verify the inferred schema and incremental keys.",
         v:"Verify idempotency by running the pipeline twice and confirming no duplicates." },
    body:"Teach dlt, the modern Python-native ingestion tool replacing hand-rolled scripts. Have me build a pipeline from the API I used earlier into Postgres or DuckDB, with schema evolution and incremental loading, and prove it is idempotent by running it twice.",
    dod:[["Built a dlt pipeline with schema evolution",null],["Proved incremental, idempotent loading",null]],
    res:[["dlt docs","docs","https://dlthub.com/docs/intro"]],
    iq:["What does dlt handle that a hand-written loader usually gets wrong?"] },

  { id:"prod-py", phase:"py", title:"Production-Grade Python", kind:"lesson", off:[70,90], prereq:["wrangling"], est:"4-5 hrs", badges:["standards"],
    goal:"Typing, pydantic, logging, config, testing with pytest, packaging, and pre-commit.",
    obj:["Add type hints and validate data with pydantic.",
         "Structure logging, config, and secrets properly.",
         "Test with pytest and package a module cleanly."],
    ai:{ t:"Generate the tests", p:"Have an agent draft pytest cases and type hints, then you review for real coverage, not just green checks.",
         v:"Verify tests actually fail when the code is broken - mutate a line and watch a test go red." },
    body:"Teach me to write data code like a professional: type hints, pydantic models, structured logging, 12-factor config, secrets handling, pytest, packaging with uv, and pre-commit hooks. Refactor one of my earlier scripts up to this standard.",
    dod:[["Added types, pydantic validation, and logging","std"],["Wrote pytest tests that fail on a real bug","std"],["Configured pre-commit and clean packaging","std"]],
    res:[["pydantic","docs","https://docs.pydantic.dev/"],["pytest","docs","https://docs.pytest.org/"]],
    iq:["Why validate data at the boundary with something like pydantic?","What makes a test suite trustworthy?"] },

  { id:"db-py", phase:"py", title:"Databases from Python", kind:"lesson", off:[200,20], prereq:["sql2","prod-py"], est:"2-3 hrs",
    goal:"SQLAlchemy, psycopg, connection pooling, and safe, fast bulk loads.",
    obj:["Connect to Postgres from Python safely (no SQL injection).",
         "Use connection pooling and transactions correctly.",
         "Bulk-load large datasets efficiently."],
    ai:{ t:"Safe query generation", p:"Let an agent draft parameterized queries, and check that it never string-concatenates user input.",
         v:"Verify with a deliberate injection attempt that your parameterization blocks." },
    body:"Teach me to work with Postgres from Python: SQLAlchemy Core and psycopg, parameterized queries, transactions, pooling, and efficient bulk loading. Have me load a large dataset fast and safely, then benchmark bulk vs row-by-row.",
    dod:[["Ran parameterized queries and transactions",null],["Bulk-loaded a large dataset efficiently",null]],
    res:[["SQLAlchemy","docs","https://docs.sqlalchemy.org/"],["psycopg","docs","https://www.psycopg.org/psycopg3/docs/"]],
    iq:["How do parameterized queries prevent SQL injection?","Why is row-by-row insertion slow?"] },

  { id:"m2", phase:"py", title:"Milestone 2 · Ingestion Pipeline", kind:"project", off:[210,130], prereq:["dlt","db-py"], est:"12-16 hrs", badges:["standards"],
    goal:"Pull from a live API into a warehouse/DuckDB, idempotently, tested, as a standalone repo.",
    obj:["Ingest from a live API into storage with dlt, incrementally.",
         "Test it, handle failures, and document the data flow.",
         "Ship a production-ready, portfolio-worthy repository."],
    ai:{ t:"AI-assisted, verified", p:"Use agents to scaffold the source and tests; you own reliability and the verification eval.",
         v:"Verify idempotency and data quality with automated checks that fail the run on bad data." },
    body:"Coach me to build a real ingestion pipeline as a portfolio project: a live API, incremental extraction with dlt, load to Postgres or DuckDB, tests, and a data-flow diagram. Enforce the portfolio-repo rules: README with architecture, atomic conventional commits, LICENSE, tests, no secrets, no emojis, and no references to any AI tool or to this course.",
    dod:[["Incremental, idempotent pipeline from a live API",null],["Tests and failure handling","std"],["README with a data-flow diagram; standalone repo","std"],["Atomic conventional commits and branching","std"]],
    res:[["dlt docs","docs","https://dlthub.com/docs/intro"]],
    iq:["Walk me through how your pipeline handles a mid-run failure.","How do you guarantee no duplicate rows?"],
    options:[
      { th:"finance", tt:"Crypto price pipeline", p:"Pull prices from a public API (e.g. CoinGecko) incrementally and build a clean price history." },
      { th:"transit", tt:"Transit / traffic feed", p:"Ingest a live transit or traffic API into a queryable history of the city's movement." },
      { th:"media", tt:"Reddit / YouTube pipeline", p:"Pull posts or video stats over time into a warehouse for trend analysis." } ] },

  /* ---------- 4 · Warehouse & Analytics Engineering ---------- */
  { id:"wh-concepts", phase:"wh", title:"Warehousing Concepts", kind:"lesson", off:[-220,40], prereq:["m1"], est:"2-3 hrs",
    goal:"OLAP, columnar and MPP storage, warehouse vs lake vs lakehouse, and the cost model.",
    obj:["Explain how columnar and MPP warehouses achieve their speed.",
         "Compare warehouse, lake, and lakehouse and their tradeoffs.",
         "Reason about the pay-per-compute cost model."],
    ai:{ t:"Cost reasoning", p:"Ask an agent to estimate the cost of a query pattern, then sanity-check its assumptions against real pricing.",
         v:"Verify by running a query and reading the actual bytes-scanned or credits used." },
    body:"Teach the concepts behind cloud warehouses: columnar storage, MPP, separation of storage and compute, and the cost model that punishes careless queries. Ground it so the hands-on next star makes sense.",
    dod:[["Explained columnar/MPP and separation of storage and compute",null],["Reasoned about warehouse cost drivers",null]],
    res:[["The Data Warehouse Toolkit","article","https://www.kimballgroup.com/"]],
    iq:["Why is columnar storage fast for analytics?","What does separating storage and compute buy you?"] },

  { id:"cloud-wh", phase:"wh", title:"Cloud Warehouse: Snowflake & BigQuery", kind:"lesson", off:[-110,-70], prereq:["wh-concepts"], est:"4-5 hrs",
    goal:"Hands-on with a cloud warehouse: load, query, and understand pricing on Snowflake and BigQuery.",
    obj:["Load and query data in a cloud warehouse.",
         "Understand its pricing and how to avoid runaway costs.",
         "Compare Snowflake and BigQuery at a high level."],
    ai:{ t:"Warehouse copilot", p:"Modern warehouses ship AI SQL assistants; learn to use them and to verify their output against the bill.",
         v:"Verify cost: check bytes scanned or credits for each query, not just that it returned rows." },
    body:"Get me hands-on with a cloud warehouse using a free trial or free tier. Load a dataset, query it, and inspect cost. Do a short side-by-side of Snowflake and BigQuery so I understand the multi-cloud landscape. Keep everything inside free limits and warn me before any step could cost money.",
    dod:[["Loaded and queried data in a cloud warehouse",null],["Inspected the cost of a query",null],["Compared Snowflake and BigQuery",null]],
    res:[["Snowflake free trial","docs","https://signup.snowflake.com/"],["BigQuery sandbox","docs","https://cloud.google.com/bigquery/docs/sandbox"]],
    iq:["How does BigQuery pricing differ from Snowflake's?","How do you keep warehouse costs under control?"] },

  { id:"dbt", phase:"wh", title:"dbt Fundamentals", kind:"lesson", off:[-20,60], prereq:["cloud-wh","db-py"], est:"4-5 hrs",
    goal:"Models, sources, refs, and materializations (view, table, incremental).",
    obj:["Build dbt models with ref and source and a clean DAG.",
         "Choose materializations and understand incremental models.",
         "Run and inspect a dbt project against your warehouse."],
    ai:{ t:"Scaffold a dbt project", p:"Use an agent to scaffold models and generate boilerplate, then you shape the DAG and semantics.",
         v:"Verify with dbt run and by inspecting the compiled SQL the agent produced." },
    body:"Teach dbt from scratch against the warehouse from the last star: project structure, sources, models, ref, and materializations. Have me build a small staging-to-marts DAG and run it. Explain why dbt changed analytics engineering.",
    dod:[["Built a working dbt DAG with ref and source",null],["Chose materializations deliberately",null]],
    res:[["dbt docs","docs","https://docs.getdbt.com/"]],
    iq:["What does ref() buy you over hardcoding table names?","When do you use an incremental model?"] },

  { id:"dbt-test", phase:"wh", title:"dbt Testing & Docs", kind:"lesson", off:[80,-30], prereq:["dbt"], est:"3-4 hrs", badges:["standards"],
    goal:"Tests, snapshots, exposures, and generated documentation.",
    obj:["Add generic and custom data tests to models.",
         "Capture history with snapshots; document with descriptions and exposures.",
         "Generate and read the dbt docs site and lineage graph."],
    ai:{ t:"Test generation", p:"Have an agent propose tests for each model, then you keep only the ones that assert something real.",
         v:"Verify tests catch problems by introducing bad data and watching them fail." },
    body:"Teach dbt testing and documentation: not_null, unique, relationships, accepted_values, custom tests, snapshots, exposures, and the docs site with lineage. Have me add a meaningful test suite to my project and prove a test fails on bad data.",
    dod:[["Added generic and custom tests that fail on bad data","std"],["Generated docs and read the lineage graph",null]],
    res:[["dbt tests","docs","https://docs.getdbt.com/docs/build/data-tests"]],
    iq:["Difference between a schema test and a data test?","How would you test referential integrity in dbt?"] },

  { id:"sqlmesh", phase:"wh", title:"SQLMesh & the Transformation Landscape", kind:"lesson", off:[180,-110], prereq:["dbt-test"], est:"3-4 hrs", badges:["emerging"],
    goal:"Virtual data environments, column-level lineage, and why 2026 teams weigh dbt vs SQLMesh.",
    obj:["Build the same transformation in SQLMesh and compare it to dbt.",
         "Use virtual data environments and column-level lineage.",
         "Explain the industry consolidation and what it means for your choices."],
    ai:{ t:"Two tools, one job", p:"Have an agent port a dbt model to SQLMesh so you learn both mental models, then judge the differences yourself.",
         v:"Verify equivalence: same outputs, and inspect the lineage each tool produces." },
    body:"Teach SQLMesh and how it compares to dbt: virtual environments, column-level lineage, and blue-green deploys. Note the 2026 consolidation (Fivetran acquiring dbt Labs and SQLMesh). Have me rebuild one dbt model in SQLMesh and articulate when I would choose each.",
    dod:[["Built a transformation in SQLMesh",null],["Explained dbt vs SQLMesh tradeoffs and the consolidation",null]],
    res:[["SQLMesh","docs","https://sqlmesh.readthedocs.io/"]],
    iq:["What is a virtual data environment and why is it useful?","dbt vs SQLMesh: when would you pick each?"] },

  { id:"semantic", phase:"wh", title:"Semantic / Metrics Layer", kind:"lesson", off:[190,60], prereq:["dbt"], est:"2-3 hrs", badges:["emerging"],
    goal:"Define a metric once and consume it everywhere: dbt Semantic Layer / Cube.",
    obj:["Explain why metric definitions drift without a semantic layer.",
         "Define a metric once and query it consistently.",
         "See how BI and AI tools consume the layer."],
    ai:{ t:"Metrics as contracts", p:"A semantic layer is also how you let AI tools answer business questions without hallucinating definitions.",
         v:"Verify a metric returns the same number through two different consumers." },
    body:"Teach the semantic/metrics layer: the problem of metric drift, and how defining metrics once (dbt Semantic Layer or Cube) fixes it. Have me define a couple of metrics and query them consistently.",
    dod:[["Defined metrics in a semantic layer",null],["Queried a metric from two consumers with matching results",null]],
    res:[["dbt Semantic Layer","docs","https://docs.getdbt.com/docs/build/about-metricflow"],["Cube","docs","https://cube.dev/docs"]],
    iq:["What problem does a semantic layer solve?"] },

  { id:"ae-patterns", phase:"wh", title:"Analytics-Engineering Patterns", kind:"lesson", off:[70,140], prereq:["dbt-test"], est:"2-3 hrs",
    goal:"Staging, intermediate, and marts; the medallion (bronze/silver/gold) idea.",
    obj:["Structure a project into staging, intermediate, and marts.",
         "Apply the medallion architecture to raw-to-refined flows.",
         "Name and organize models the way real teams do."],
    ai:{ t:"Refactor to layers", p:"Have an agent reorganize a flat set of models into clean layers, then you enforce naming and boundaries.",
         v:"Verify the DAG has no layer-skipping shortcuts by reading the lineage graph." },
    body:"Teach the standard layering of an analytics project: staging, intermediate, marts, and the medallion metaphor. Have me refactor my dbt project into clean layers with consistent naming.",
    dod:[["Refactored models into staging/intermediate/marts",null],["Applied consistent naming conventions","std"]],
    res:[["dbt project structure","docs","https://docs.getdbt.com/best-practices/how-we-structure/1-guide-overview"]],
    iq:["What goes in staging vs marts?","Explain bronze/silver/gold."] },

  { id:"m3", phase:"wh", title:"Milestone 3 · Analytics Engineering", kind:"project", off:[240,150], prereq:["dbt-test","ae-patterns","m2"], est:"14-18 hrs", badges:["standards"],
    goal:"Raw to tested marts with dbt or SQLMesh, documented, as a standalone portfolio repo.",
    obj:["Transform raw data into tested, documented marts.",
         "Produce a lineage graph and a docs site.",
         "Ship a production-ready, portfolio-worthy repository."],
    ai:{ t:"Scaffold, then own it", p:"Use agents for boilerplate and test suggestions; you own the model design and the tests that matter.",
         v:"Verify the marts answer real questions and every test fails on planted bad data." },
    body:"Coach me to build an analytics-engineering project on the data from Milestone 2: staging to marts with dbt or SQLMesh (my choice, justified), a real test suite, and generated docs with lineage. Enforce the portfolio-repo rules throughout: README with architecture and a lineage screenshot, atomic conventional commits, LICENSE, no emojis, and no references to any AI tool or to this course.",
    dod:[["Raw-to-marts with tests and docs",null],["Lineage graph produced",null],["Chose and justified dbt vs SQLMesh",null],["Standalone repo: README, atomic commits, LICENSE, no AI/course references","std"]],
    res:[["dbt docs","docs","https://docs.getdbt.com/"]],
    iq:["Walk me through your model layers and one design decision.","How do your tests protect downstream consumers?"],
    options:[
      { th:"finance", tt:"Personal finance analytics", p:"Turn raw transactions into marts: monthly spend by category, cashflow, trends." },
      { th:"media / gaming", tt:"Gaming or esports stats", p:"Model match/player data into marts answering performance and meta questions." },
      { th:"cs / cloud", tt:"BigQuery public dataset", p:"Build the marts on a BigQuery public dataset for a multi-cloud portfolio piece." } ] },

  /* ---------- 5 · Orchestration & DataOps ---------- */
  { id:"orch-concepts", phase:"orch", title:"Orchestration Concepts", kind:"lesson", off:[-210,-30], prereq:["m2"], est:"2-3 hrs",
    goal:"DAGs, scheduling, idempotency, backfills, retries, and SLAs.",
    obj:["Explain DAGs, scheduling, and dependencies.",
         "Design idempotent tasks that support safe backfills and retries.",
         "Define an SLA for a pipeline and what to do when it is missed."],
    ai:{ t:"Idempotency by design", p:"Ask an agent to critique a task for idempotency; you decide how to make re-runs safe.",
         v:"Verify idempotency by running a task twice and confirming identical state." },
    body:"Teach the concepts every orchestrator shares: DAGs, scheduling, idempotency, backfills, retries, and SLAs. Use examples so the Airflow and Dagster stars land. Emphasize why idempotency is non-negotiable.",
    dod:[["Explained idempotency, backfills, and retries",null],["Defined an SLA for a pipeline",null]],
    res:[["Airflow concepts","docs","https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/index.html"]],
    iq:["Why must pipeline tasks be idempotent?","What is a backfill and when do you run one?"] },

  { id:"airflow", phase:"orch", title:"Airflow Fundamentals", kind:"lesson", off:[-90,-120], prereq:["orch-concepts"], est:"4-5 hrs",
    goal:"Operators, task dependencies, the TaskFlow API, connections, and XComs.",
    obj:["Build a DAG with operators and dependencies.",
         "Use the TaskFlow API and pass data with XComs.",
         "Manage connections and variables."],
    ai:{ t:"Draft, then harden", p:"Have an agent draft a DAG; you fix scheduling, retries, and idempotency it will get wrong.",
         v:"Verify by running the DAG locally and reading the task logs, not just the graph view." },
    body:"Teach Airflow hands-on with a local Docker setup: DAGs, operators, dependencies, the TaskFlow API, connections, and XComs. Have me orchestrate the ingestion-plus-transform flow from earlier milestones on a schedule.",
    dod:[["Built and ran a scheduled DAG locally",null],["Used the TaskFlow API and connections",null]],
    res:[["Airflow","docs","https://airflow.apache.org/docs/"]],
    iq:["What is an XCom and when should you avoid large ones?"] },

  { id:"airflow-prac", phase:"orch", title:"Airflow in Practice", kind:"lesson", off:[10,-20], prereq:["airflow"], est:"3-4 hrs",
    goal:"Sensors, dynamic DAGs, deferrable operators, and common anti-patterns.",
    obj:["Use sensors and deferrable operators correctly.",
         "Generate DAGs dynamically without creating a mess.",
         "Avoid the classic Airflow anti-patterns."],
    ai:{ t:"Anti-pattern radar", p:"Ask an agent to review a DAG for anti-patterns; you confirm which critiques are real.",
         v:"Verify fixes by observing scheduler behavior and task duration, not assumptions." },
    body:"Teach production Airflow patterns: sensors, deferrable operators, dynamic task mapping, and the anti-patterns (top-level code, heavy XComs, non-idempotent tasks). Have me harden my DAG from the previous star.",
    dod:[["Used a sensor and a deferrable operator",null],["Removed an anti-pattern from a DAG",null]],
    res:[["Astronomer best practices","article","https://www.astronomer.io/docs/learn/dag-best-practices/"]],
    iq:["Why is top-level code in a DAG file dangerous?"] },

  { id:"dagster", phase:"orch", title:"Dagster (Asset-Based)", kind:"lesson", off:[120,-110], prereq:["airflow"], est:"3-4 hrs", badges:["emerging"],
    goal:"Software-defined assets - where many new teams start - plus a note on Prefect and Kestra.",
    obj:["Model pipelines as software-defined assets.",
         "Compare the asset mental model to Airflow's task model.",
         "Know where Prefect and Kestra fit."],
    ai:{ t:"Port and compare", p:"Have an agent port an Airflow DAG to Dagster assets so you feel both paradigms.",
         v:"Verify both produce the same materialized outputs before judging ergonomics." },
    body:"Teach Dagster's asset-based approach and contrast it with Airflow. Have me rebuild a small pipeline as software-defined assets and explain when I would choose Dagster, Airflow, Prefect, or Kestra.",
    dod:[["Built a pipeline as Dagster assets",null],["Explained asset vs task orchestration",null]],
    res:[["Dagster","docs","https://docs.dagster.io/"]],
    iq:["What is a software-defined asset?","When would you choose Dagster over Airflow?"] },

  { id:"dq-obs", phase:"orch", title:"Data Quality & Observability", kind:"lesson", off:[60,100], prereq:["dbt-test"], est:"3-4 hrs", badges:["standards"],
    goal:"Freshness, volume, and schema checks; Great Expectations; alerting and data downtime.",
    obj:["Add freshness, volume, and schema monitors to a pipeline.",
         "Use Great Expectations or similar for validation.",
         "Alert on failures and think in terms of data downtime."],
    ai:{ t:"Generate expectations", p:"Have an agent propose data expectations from a sample; you keep the ones that reflect real invariants.",
         v:"Verify each check fires by feeding it violating data." },
    body:"Teach data quality and observability: the monitors that matter (freshness, volume, schema, distribution), Great Expectations, alerting, and the concept of data downtime. Have me instrument a pipeline so a bad load pages me instead of silently corrupting a dashboard.",
    dod:[["Added freshness/volume/schema checks that alert","std"],["Validated data with Great Expectations",null]],
    res:[["Great Expectations","docs","https://docs.greatexpectations.io/"]],
    iq:["What is data downtime and how do you measure it?","Which monitors catch the most real incidents?"] },

  { id:"contracts", phase:"orch", title:"Data Contracts & DataOps", kind:"lesson", off:[190,30], prereq:["dq-obs"], est:"2-3 hrs", badges:["emerging","standards"],
    goal:"Contracts between producers and consumers, shift-left validation, CI for data, and environments.",
    obj:["Define a data contract and enforce it in CI.",
         "Shift validation left, toward the producer.",
         "Separate dev, staging, and prod for data."],
    ai:{ t:"Contract from schema", p:"Use an agent to draft a contract from an existing schema; you decide the guarantees worth promising.",
         v:"Verify the contract is enforced by breaking it in a branch and watching CI fail." },
    body:"Teach data contracts and DataOps: agreeing on schema and semantics between producers and consumers, enforcing it in CI, shifting validation left, and running dev/staging/prod environments. Have me add a contract check to a pipeline's CI.",
    dod:[["Defined and enforced a data contract in CI","std"],["Separated environments for a pipeline","std"]],
    res:[["Data contracts","article","https://www.datacontract.com/"]],
    iq:["What does a data contract guarantee?","Why enforce contracts in CI rather than at read time?"] },

  { id:"m4", phase:"orch", title:"Milestone 4 · Orchestrated ELT", kind:"project", off:[230,140], prereq:["airflow-prac","dq-obs","m3"], est:"12-16 hrs", badges:["standards"],
    goal:"Put ingestion + transform on a schedule with quality gates, alerting, and CI, as a standalone repo.",
    obj:["Schedule the full ingest-to-marts flow with retries and backfills.",
         "Add quality gates that stop bad data and alert you.",
         "Ship a repo with CI and an incident runbook."],
    ai:{ t:"Assist, then operate", p:"Use agents for DAG boilerplate; you own scheduling, idempotency, and the runbook.",
         v:"Verify by deliberately breaking a run and confirming the alert and the runbook work." },
    body:"Coach me to orchestrate the earlier milestones end to end: schedule ingest to warehouse to transform, add quality gates and alerting, and run tests in CI. Enforce the portfolio-repo rules: README with an architecture diagram, a what-happens-when-it-breaks runbook, atomic conventional commits, no emojis, and no references to any AI tool or to this course.",
    dod:[["Scheduled ELT with retries and backfills",null],["Quality gates and alerting that actually fire","std"],["CI running tests; incident runbook","std"],["Standalone repo with architecture diagram; no AI/course references","std"]],
    res:[["Airflow","docs","https://airflow.apache.org/docs/"]],
    iq:["Walk me through what happens when a nightly load fails at 3am.","How do you backfill safely after an outage?"],
    options:[
      { th:"any", tt:"Schedule your own stack", p:"Orchestrate your Milestone 2 + 3 pipeline into a reliable, monitored nightly job." } ] },

  /* ---------- 6 · AWS Cloud & Lakehouse ---------- */
  { id:"aws", phase:"cloud", title:"AWS Foundations for DE", kind:"lesson", off:[-210,10], prereq:["m2"], est:"3-4 hrs", badges:["standards"],
    goal:"IAM and least privilege, S3, regions, billing and cost alarms, the CLI and boto3.",
    obj:["Set up IAM with least privilege and avoid root-account mistakes.",
         "Use S3, the AWS CLI, and boto3.",
         "Set a billing alarm so nothing surprises you."],
    ai:{ t:"IAM without footguns", p:"Have an agent draft least-privilege IAM policies; you verify they grant exactly what is needed and no more.",
         v:"Verify a policy by testing an action it should allow and one it should deny." },
    body:"Teach AWS foundations for data work: the account and IAM model, least privilege, S3 basics, regions, the CLI and boto3, and a billing alarm. Everything inside the free tier, with clear warnings before anything could cost money.",
    dod:[["IAM user/role with least privilege","std"],["Used S3 via CLI and boto3",null],["Billing alarm configured","std"]],
    res:[["AWS free tier","docs","https://aws.amazon.com/free/"],["IAM best practices","docs","https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html"]],
    iq:["What is least privilege and why does it matter?","Difference between an IAM user and a role?"] },

  { id:"s3-lake", phase:"cloud", title:"Data Lakes on S3", kind:"lesson", off:[-100,-100], prereq:["aws"], est:"3-4 hrs",
    goal:"Partitioning, file layout, the Glue Data Catalog, and querying with Athena.",
    obj:["Lay out a lake on S3 with sensible partitioning.",
         "Catalog data with Glue and query it with Athena.",
         "Understand file-size and partition tradeoffs."],
    ai:{ t:"Layout advisor", p:"Ask an agent to propose a partition scheme for a query pattern; you validate against real query costs.",
         v:"Verify with Athena: check the data scanned for a partitioned vs unpartitioned query." },
    body:"Teach data lakes on S3: partitioning, file sizing, the Glue Data Catalog, and querying with Athena. Have me land Parquet in a partitioned layout and query it, then measure how partitioning cuts data scanned.",
    dod:[["Landed partitioned Parquet in S3",null],["Queried it via Athena and measured data scanned",null]],
    res:[["Amazon Athena","docs","https://docs.aws.amazon.com/athena/"]],
    iq:["How does partitioning reduce query cost?","What is the small-files problem?"] },

  { id:"serverless", phase:"cloud", title:"Serverless ETL", kind:"lesson", off:[0,-30], prereq:["s3-lake"], est:"3-4 hrs",
    goal:"AWS Glue (Spark), Lambda, Step Functions, and EventBridge schedules.",
    obj:["Run a Glue Spark job for a transformation.",
         "Use Lambda and Step Functions for lightweight ETL orchestration.",
         "Schedule work with EventBridge."],
    ai:{ t:"Glue script drafting", p:"Have an agent draft a Glue job; you verify partitioning, bookmarks, and cost.",
         v:"Verify output correctness and cost in a small run before scaling." },
    body:"Teach serverless ETL on AWS: a Glue Spark job, a Lambda for light transforms, Step Functions to coordinate, and EventBridge to schedule. Keep runs tiny and inside free-tier limits.",
    dod:[["Ran a Glue job that writes to the lake",null],["Coordinated steps with Step Functions",null]],
    res:[["AWS Glue","docs","https://docs.aws.amazon.com/glue/"]],
    iq:["When would you use Glue vs a Lambda for ETL?"] },

  { id:"iceberg", phase:"cloud", title:"Lakehouse & Apache Iceberg", kind:"lesson", off:[110,-110], prereq:["s3-lake","dbt-test"], est:"4-5 hrs", badges:["emerging"],
    goal:"Iceberg (the ~78% default table format, V3), catalogs, time travel, and schema evolution.",
    obj:["Explain what a table format adds over raw Parquet.",
         "Use Iceberg for time travel and schema evolution.",
         "Understand catalogs (Glue, Polaris, Unity, Lakekeeper) and DuckLake."],
    ai:{ t:"Format landscape", p:"Have an agent summarize Iceberg vs Delta vs Hudi and DuckLake; you verify claims against the docs.",
         v:"Verify time travel and schema evolution by doing them and querying an older snapshot." },
    body:"Teach the lakehouse and Apache Iceberg: why table formats exist, ACID on a lake, time travel, and schema evolution. Cover catalogs (Glue, Polaris, Unity, Lakekeeper) and the simpler emerging DuckLake. Have me create an Iceberg table, evolve its schema, and time-travel a query.",
    dod:[["Created an Iceberg table and evolved its schema",null],["Time-traveled to a previous snapshot",null],["Can explain catalogs and DuckLake",null]],
    res:[["Apache Iceberg","docs","https://iceberg.apache.org/docs/latest/"]],
    iq:["What does Iceberg add over plain Parquet on S3?","What is a catalog in the lakehouse world?"] },

  { id:"redshift", phase:"cloud", title:"Warehousing on AWS", kind:"lesson", off:[130,70], prereq:["aws","wh-concepts"], est:"2-3 hrs",
    goal:"Redshift and Redshift Serverless, and when to choose them vs Snowflake.",
    obj:["Load and query data in Redshift Serverless.",
         "Understand distribution and sort keys.",
         "Reason about Redshift vs Snowflake vs a lakehouse."],
    ai:{ t:"Key selection", p:"Ask an agent to suggest distribution and sort keys; you verify against the query patterns.",
         v:"Verify with the query plan that keys are actually being used." },
    body:"Teach Redshift and Redshift Serverless: loading, distribution and sort keys, and when Redshift makes sense versus Snowflake or an Iceberg lakehouse. Keep the exercise inside free-tier or serverless credits, with cost warnings.",
    dod:[["Loaded and queried data in Redshift Serverless",null],["Explained Redshift vs Snowflake tradeoffs",null]],
    res:[["Amazon Redshift","docs","https://docs.aws.amazon.com/redshift/"]],
    iq:["What are distribution and sort keys for?","When would you not use Redshift?"] },

  { id:"iac", phase:"cloud", title:"Infrastructure as Code (Terraform)", kind:"lesson", off:[-40,110], prereq:["aws"], est:"4-5 hrs", badges:["standards"],
    goal:"Terraform for reproducible data infrastructure - and portfolio gold.",
    obj:["Provision S3, IAM, and Glue with Terraform.",
         "Manage state, variables, and modules cleanly.",
         "Make infrastructure reproducible and reviewable."],
    ai:{ t:"IaC from a description", p:"Have an agent generate Terraform from a described architecture, then you review every resource critically before apply.",
         v:"Verify with terraform plan; never apply AI-generated infra you have not read." },
    body:"Teach Terraform for data infrastructure: providers, resources, state, variables, and modules. Have me provision the S3 bucket, IAM role, and Glue catalog for my lake as code, review the plan carefully, and tear it down cleanly.",
    dod:[["Provisioned lake infra with Terraform","std"],["Read a plan carefully before applying","std"],["Tore everything down cleanly to avoid cost","std"]],
    res:[["Terraform","docs","https://developer.hashicorp.com/terraform/docs"]],
    iq:["Why is IaC better than clicking in the console?","What is Terraform state and why does it matter?"] },

  { id:"containers", phase:"cloud", title:"Containers & CI/CD for Data", kind:"lesson", off:[210,-20], prereq:["iac","prod-py"], est:"3-4 hrs", badges:["standards"],
    goal:"Docker images, a taste of ECS/Fargate, and GitHub Actions pipelines.",
    obj:["Containerize a data job with a clean Dockerfile.",
         "Run tests and lint in GitHub Actions.",
         "Understand deploying a container to ECS/Fargate."],
    ai:{ t:"Pipeline authoring", p:"Have an agent draft a CI workflow; you verify it fails on real breakage, not just runs green.",
         v:"Verify CI catches a bug by pushing a broken commit to a branch." },
    body:"Teach containerization and CI/CD for data: a production Dockerfile, GitHub Actions running tests and lint on every push, and the idea of deploying to ECS/Fargate. Have me add a CI pipeline to one of my project repos.",
    dod:[["Containerized a data job",null],["GitHub Actions running tests and lint on push","std"]],
    res:[["GitHub Actions","docs","https://docs.github.com/actions"]],
    iq:["What should CI run on every pull request for a data repo?"] },

  { id:"m5", phase:"cloud", title:"Milestone 5 · Cloud Lakehouse Platform", kind:"project", off:[240,120], prereq:["iceberg","iac","containers","m4"], est:"20-28 hrs", badges:["standards"],
    goal:"Ingest to an S3 Iceberg lake to a warehouse, all Terraform, all CI - your centerpiece repo.",
    obj:["Build ingest to S3 Iceberg lake to Glue/Athena to a warehouse.",
         "Provision everything with Terraform and run it through CI.",
         "Produce a full architecture diagram and a hiring-manager README."],
    ai:{ t:"Multiply, then verify", p:"Use agents heavily for IaC and glue code; you review every resource and own the architecture.",
         v:"Verify with terraform plan and end-to-end test runs; never apply unread infra." },
    body:"Coach me to build the centerpiece: a cloud-native lakehouse. Ingest with dlt into an S3 Iceberg lake (partitioned), catalog and query with Glue/Athena, and land curated data in a warehouse, all provisioned with Terraform and exercised by CI. Enforce the portfolio-repo rules hard: a README a hiring manager can skim, a full architecture diagram, atomic conventional commits, a branching strategy, LICENSE, no emojis, and no references to any AI tool or to this course.",
    dod:[["Ingest -> S3 Iceberg -> Glue/Athena -> warehouse working",null],["All infra in Terraform; CI runs it","std"],["Full architecture diagram and skimmable README","std"],["Atomic conventional commits and branching; no AI/course references","std"]],
    res:[["Apache Iceberg","docs","https://iceberg.apache.org/docs/latest/"],["Terraform AWS","docs","https://registry.terraform.io/providers/hashicorp/aws/latest/docs"]],
    iq:["Present this platform as a system design in five minutes.","What would you change to handle 10x the data or cost?"],
    options:[
      { th:"transit", tt:"Mobility lakehouse", p:"A lakehouse over transit/traffic data with time-travel analysis of how the city moves." },
      { th:"finance", tt:"Markets lakehouse", p:"Ingest market or crypto data into an Iceberg lake with curated analytics marts." },
      { th:"media", tt:"Media lakehouse", p:"A lakehouse over listening/viewing/gaming data with rich historical marts." } ] },

  /* ---------- 7 · Big Data & Streaming ---------- */
  { id:"dist", phase:"stream", title:"Distributed Computing Concepts", kind:"lesson", off:[-210,-20], prereq:["m3"], est:"2-3 hrs",
    goal:"Partitioning, shuffles, the MapReduce lineage, and when you actually need Spark.",
    obj:["Explain partitioning and why shuffles are expensive.",
         "Trace the lineage from MapReduce to Spark.",
         "Judge honestly when distributed compute is warranted vs DuckDB/Polars."],
    ai:{ t:"Right-size the tool", p:"Have an agent argue for and against Spark for a workload; you make the call based on real data size.",
         v:"Verify by estimating data size: most single-machine problems do not need a cluster." },
    body:"Teach the concepts behind distributed data processing: partitioning, shuffles, and the MapReduce-to-Spark lineage. Be honest that in 2026 many workloads fit on one machine (DuckDB/Polars) and Spark is for genuinely large data.",
    dod:[["Explained partitioning and shuffles",null],["Can decide when Spark is actually needed",null]],
    res:[["Spark overview","docs","https://spark.apache.org/docs/latest/"]],
    iq:["Why are shuffles the expensive part of distributed jobs?","When do you not need Spark?"] },

  { id:"spark", phase:"stream", title:"Spark / PySpark", kind:"lesson", off:[-90,-120], prereq:["dist"], est:"5-6 hrs",
    goal:"DataFrames, transformations vs actions, Spark SQL, tuning basics, and reading the UI.",
    obj:["Write PySpark DataFrame code and Spark SQL.",
         "Distinguish transformations from actions and understand lazy execution.",
         "Read the Spark UI to find a bottleneck."],
    ai:{ t:"Debug the DAG", p:"Have an agent interpret the Spark UI and suggest a tuning change; you confirm it against the physical plan.",
         v:"Verify a tuning change by measuring stage time before and after." },
    body:"Teach PySpark hands-on locally: DataFrames, transformations vs actions, lazy execution, Spark SQL, joins and skew, and reading the Spark UI. Have me process a large dataset and diagnose one performance issue from the UI.",
    dod:[["Processed a large dataset with PySpark",null],["Diagnosed a bottleneck from the Spark UI",null]],
    res:[["PySpark","docs","https://spark.apache.org/docs/latest/api/python/"]],
    iq:["Transformation vs action in Spark?","What causes and how do you fix data skew?"] },

  { id:"stream-concepts", phase:"stream", title:"Streaming Concepts", kind:"lesson", off:[10,-30], prereq:["dist"], est:"2-3 hrs",
    goal:"Batch vs stream, event time vs processing time, windows, and exactly-once.",
    obj:["Contrast batch and streaming and when each fits.",
         "Reason about event time, watermarks, and windows.",
         "Explain delivery guarantees and exactly-once."],
    ai:{ t:"Semantics check", p:"Have an agent explain a windowing scenario; you verify against the actual semantics of late data.",
         v:"Verify understanding by predicting output for out-of-order events, then testing it." },
    body:"Teach streaming fundamentals: batch vs stream, event vs processing time, watermarks, windowing (tumbling, sliding, session), and delivery guarantees. Use concrete examples with late and out-of-order events.",
    dod:[["Explained event time and watermarks",null],["Reasoned about exactly-once vs at-least-once",null]],
    res:[["Streaming systems (concepts)","article","https://www.oreilly.com/library/view/streaming-systems/9781491983867/"]],
    iq:["Event time vs processing time?","How do watermarks handle late data?"] },

  { id:"kafka", phase:"stream", title:"Apache Kafka", kind:"lesson", off:[120,-120], prereq:["stream-concepts"], est:"4-5 hrs",
    goal:"Topics, partitions, producers and consumers, consumer groups, and backpressure.",
    obj:["Produce to and consume from Kafka topics.",
         "Understand partitions, offsets, and consumer groups.",
         "Reason about ordering, throughput, and backpressure."],
    ai:{ t:"Client scaffolding", p:"Have an agent scaffold producer/consumer code; you verify delivery semantics and error handling.",
         v:"Verify by killing a consumer mid-stream and confirming offsets resume correctly." },
    body:"Teach Kafka hands-on with a local Docker setup (Kafka or Redpanda): topics, partitions, producers, consumers, consumer groups, offsets, and backpressure. Have me build a producer and consumer and observe rebalancing.",
    dod:[["Produced and consumed from a Kafka topic",null],["Observed consumer-group rebalancing and offsets",null]],
    res:[["Apache Kafka","docs","https://kafka.apache.org/documentation/"],["Redpanda","docs","https://docs.redpanda.com/"]],
    iq:["How do partitions relate to ordering and parallelism?","What is a consumer group?"] },

  { id:"stream-proc", phase:"stream", title:"Stream Processing", kind:"lesson", off:[150,60], prereq:["kafka","spark"], est:"3-4 hrs",
    goal:"Spark Structured Streaming and a taste of Flink.",
    obj:["Build a streaming job with windowed aggregations.",
         "Handle state and late data.",
         "Know where Flink fits vs Spark Structured Streaming."],
    ai:{ t:"Stateful streaming help", p:"Have an agent draft a windowed aggregation; you verify state and watermark handling.",
         v:"Verify by feeding late events and checking the windows update correctly." },
    body:"Teach stream processing with Spark Structured Streaming (and a Flink taste): consuming from Kafka, windowed aggregations, stateful processing, and handling late data. Have me build a job that aggregates a live stream into a rolling metric.",
    dod:[["Built a windowed streaming aggregation from Kafka",null],["Handled late data with a watermark",null]],
    res:[["Structured Streaming","docs","https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html"],["Apache Flink","docs","https://flink.apache.org/"]],
    iq:["How does Structured Streaming handle state?","Spark Structured Streaming vs Flink?"] },

  { id:"realtime-db", phase:"stream", title:"Real-Time Analytics Databases", kind:"lesson", off:[10,110], prereq:["kafka"], est:"2-3 hrs", badges:["emerging"],
    goal:"ClickHouse, Tinybird, and DuckDB for sub-second analytics over streaming data.",
    obj:["Explain the real-time OLAP layer and why it exists.",
         "Ingest a stream into ClickHouse and query it fast.",
         "Compare real-time OLAP to a batch warehouse."],
    ai:{ t:"Schema for speed", p:"Have an agent propose a ClickHouse schema and ordering key; you verify against query latency.",
         v:"Verify sub-second latency on a realistic query volume." },
    body:"Teach the real-time analytics layer: ClickHouse (and Tinybird, DuckDB) for sub-second queries over fresh streaming data. Have me ingest a stream into ClickHouse and hit sub-second queries, then contrast with a batch warehouse.",
    dod:[["Ingested a stream into ClickHouse",null],["Achieved sub-second analytical queries",null]],
    res:[["ClickHouse","docs","https://clickhouse.com/docs"]],
    iq:["Why is ClickHouse fast for real-time analytics?","When do you need real-time OLAP vs a warehouse?"] },

  { id:"m6", phase:"stream", title:"Milestone 6 · Real-Time Pipeline", kind:"project", off:[240,130], prereq:["stream-proc","realtime-db","m5"], est:"18-24 hrs", badges:["standards"],
    goal:"Live events to Kafka to a stream processor to ClickHouse to a live dashboard - a standalone repo.",
    obj:["Ingest live events and process them in a stream.",
         "Serve fresh results to a live dashboard.",
         "Handle backpressure and late data; ship a clean repo with a recorded demo."],
    ai:{ t:"Assist, then verify latency", p:"Use agents for boilerplate; you own correctness under load and late data.",
         v:"Verify end to end: push a burst of events and confirm the dashboard stays correct and fresh." },
    body:"Coach me to build a real-time pipeline: a live event source to Kafka, a stream processor, into ClickHouse or a warehouse, feeding a live dashboard. Handle backpressure and late data. Enforce the portfolio-repo rules and include a short recorded demo clip. README with architecture, atomic conventional commits, no emojis, and no references to any AI tool or to this course.",
    dod:[["Live events -> Kafka -> processing -> store -> dashboard",null],["Handled backpressure and late data",null],["Recorded demo clip and architecture diagram","std"],["Standalone repo with atomic commits; no AI/course references","std"]],
    res:[["Kafka","docs","https://kafka.apache.org/documentation/"]],
    iq:["Walk me through your pipeline under a sudden traffic spike.","How do you guarantee the dashboard is not stale?"],
    options:[
      { th:"finance", tt:"Live crypto trades", p:"Stream live trades into a real-time dashboard of price and volume." },
      { th:"transit", tt:"Live transit map", p:"Stream vehicle positions into a live map of the city's traffic in motion." },
      { th:"media / gaming", tt:"Live match events", p:"Stream live match or game events into a real-time stats dashboard." } ] },

  /* ---------- 8 · AI & LLM Engineering ---------- */
  { id:"ml-fund", phase:"llm", title:"ML Fundamentals for Engineers", kind:"lesson", off:[-260,60], prereq:["db-py"], est:"5-6 hrs",
    goal:"The ML lifecycle, train/val/test, metrics, overfitting, feature engineering; one clean sklearn model.",
    obj:["Explain the ML lifecycle and train/validation/test splits.",
         "Choose metrics and diagnose overfitting.",
         "Build one clean end-to-end scikit-learn model."],
    ai:{ t:"Baseline fast", p:"Use an agent to scaffold a modeling notebook; you own the evaluation and the honest read of the metrics.",
         v:"Verify no leakage: confirm the test set never touched training or feature fitting." },
    body:"Teach ML fundamentals for an engineer, enough to be credible without going down a research hole: the lifecycle, splits, metrics, overfitting, and feature engineering. Have me build one clean end-to-end scikit-learn model and evaluate it honestly.",
    dod:[["Built and evaluated one sklearn model",null],["Explained overfitting and how you checked for leakage",null]],
    res:[["scikit-learn","docs","https://scikit-learn.org/stable/"]],
    iq:["What is data leakage and how do you prevent it?","How do you pick a metric for an imbalanced problem?"] },

  { id:"ml-pipe", phase:"llm", title:"ML Data Pipelines & Feature Stores", kind:"lesson", off:[-160,-60], prereq:["ml-fund","m3"], est:"3-4 hrs",
    goal:"How data engineering feeds ML: training-data pipelines and the feature-store idea (Feast).",
    obj:["Build a reproducible training-data pipeline.",
         "Explain the offline/online skew problem a feature store solves.",
         "Version features and datasets."],
    ai:{ t:"Pipeline scaffolding", p:"Have an agent scaffold a feature pipeline; you enforce reproducibility and point-in-time correctness.",
         v:"Verify point-in-time correctness so features never leak future information." },
    body:"Teach how DE feeds ML: building reproducible training-data pipelines, point-in-time correctness, and what a feature store (Feast) provides. Have me turn one of my datasets into a versioned, reproducible training set.",
    dod:[["Built a reproducible training-data pipeline",null],["Explained offline/online skew and feature stores",null]],
    res:[["Feast","docs","https://docs.feast.dev/"]],
    iq:["What is offline/online skew?","Why is point-in-time correctness critical for features?"] },

  { id:"mlops", phase:"llm", title:"MLOps", kind:"lesson", off:[-40,-130], prereq:["ml-fund","containers"], est:"4-5 hrs", badges:["standards"],
    goal:"Experiment tracking (MLflow), model registry, packaging, serving (FastAPI), monitoring, and drift.",
    obj:["Track experiments and register models with MLflow.",
         "Serve a model behind a FastAPI endpoint.",
         "Monitor for drift and performance decay."],
    ai:{ t:"Serve and monitor", p:"Use an agent to scaffold serving and monitoring; you own the reproducibility and the alerts.",
         v:"Verify the served model matches the tracked one by comparing predictions on a fixed set." },
    body:"Teach MLOps: MLflow for tracking and a model registry, packaging a model, serving it with FastAPI, and monitoring for drift. Have me take my earlier model, track it, serve it, and add a basic drift monitor.",
    dod:[["Tracked experiments and registered a model with MLflow","std"],["Served the model via FastAPI",null],["Added a drift monitor",null]],
    res:[["MLflow","docs","https://mlflow.org/docs/latest/index.html"],["FastAPI","docs","https://fastapi.tiangolo.com/"]],
    iq:["What does a model registry give you?","How do you detect model drift in production?"] },

  { id:"embeddings", phase:"llm", title:"Embeddings & Vector Databases", kind:"lesson", off:[-70,60], prereq:["ml-fund"], est:"3-4 hrs",
    goal:"What embeddings are, similarity search, and pgvector / Qdrant / Pinecone with hybrid search.",
    obj:["Explain embeddings and vector similarity.",
         "Store and query vectors in a vector database.",
         "Combine vector and keyword search (hybrid)."],
    ai:{ t:"Embedding pipelines", p:"Use an agent to build an embedding-and-index pipeline; you verify retrieval quality on real queries.",
         v:"Verify retrieval by inspecting the top-k results for known queries, not just that it runs." },
    body:"Teach embeddings and vector databases: what an embedding is, cosine similarity, indexing (HNSW), and hybrid search. Have me embed a real corpus, index it in pgvector or Qdrant, and evaluate retrieval quality on sample queries.",
    dod:[["Embedded a corpus and indexed it in a vector DB",null],["Ran and evaluated similarity and hybrid search",null]],
    res:[["pgvector","repo","https://github.com/pgvector/pgvector"],["Qdrant","docs","https://qdrant.tech/documentation/"]],
    iq:["What does an embedding represent?","Why combine vector and keyword search?"] },

  { id:"rag", phase:"llm", title:"RAG · Foundations to Advanced", kind:"lesson", off:[70,-40], prereq:["embeddings"], est:"6-7 hrs", badges:["emerging","ai"],
    goal:"Chunking, retrieval, reranking, grounding - then agentic RAG, GraphRAG, and query rewriting.",
    obj:["Build a solid baseline RAG pipeline.",
         "Improve it with reranking, query rewriting, agentic RAG, and GraphRAG.",
         "Make it survive messy data, ambiguous queries, and corpus drift."],
    ai:{ t:"The highest-value AI skill", p:"Most enterprise AI is RAG. The hard part is not a demo; it is a RAG that stays correct as the corpus changes.",
         v:"Verify with an eval harness (see the next star): retrieval and generation measured separately, no vibes." },
    body:"Teach RAG from foundations to advanced: chunking strategies, retrieval, reranking, grounding and citations, then agentic RAG, GraphRAG, and query rewriting. Build it on my own data. Then break it on purpose (ambiguous queries, updated corpus) and fix it.",
    dod:[["Built a baseline RAG over my own corpus",null],["Added reranking/query rewriting and measured the lift",null],["Documented failure modes and a drift plan","std"]],
    res:[["LlamaIndex","docs","https://docs.llamaindex.ai/"],["RAG techniques","repo","https://github.com/NirDiamant/RAG_Techniques"]],
    iq:["Retrieval looks fine but answers are wrong - how do you debug?","How does agentic RAG differ from a single retrieval pass?"] },

  { id:"eval-llm", phase:"llm", title:"Evaluating LLM Systems", kind:"lesson", off:[190,-120], prereq:["rag"], est:"3-4 hrs", badges:["emerging","standards"],
    goal:"LLM-as-judge, ragas, offline vs online evals, and regression suites.",
    obj:["Build an eval set and score a RAG or LLM system.",
         "Use LLM-as-judge responsibly and know its limits.",
         "Run evals as a regression gate on every change."],
    ai:{ t:"Evals are the product", p:"This is the discipline that separates real AI engineers from demo builders: you cannot improve what you cannot measure.",
         v:"Verify the eval itself: confirm it ranks a deliberately worse system lower." },
    body:"Teach LLM evaluation: building a labelled eval set, LLM-as-judge and its pitfalls, ragas for RAG, offline vs online evaluation, and wiring evals into CI as a regression gate. Have me build an eval harness for my RAG system and make it block a regression.",
    dod:[["Built an eval set and scored my system","std"],["Wired evals into a regression gate","std"]],
    res:[["ragas","docs","https://docs.ragas.io/"],["Evals guide","article","https://hamel.dev/blog/posts/evals/"]],
    iq:["How do you evaluate RAG offline vs online?","What are the failure modes of LLM-as-judge?"] },

  { id:"llm-apps", phase:"llm", title:"LLM Apps, Agents & Orchestration", kind:"lesson", off:[180,20], prereq:["rag"], est:"4-5 hrs", badges:["emerging"],
    goal:"LangChain/LlamaIndex, tool use, structured outputs, and multi-agent patterns.",
    obj:["Build an LLM app with tool use and structured outputs.",
         "Design a simple multi-agent workflow.",
         "Manage prompts and versions like code."],
    ai:{ t:"Build the app", p:"You are now building the AI systems, not just using them; apply everything from the AI-Assisted constellation.",
         v:"Verify tool calls and structured outputs against schemas; never trust free-form model text as data." },
    body:"Teach building real LLM applications: tool use, structured outputs (JSON schema), agent patterns, and light multi-agent orchestration, with prompt and version management. Have me build a small agentic app that calls tools and returns validated structured data.",
    dod:[["Built an LLM app with tool use and structured outputs",null],["Versioned prompts like code","std"]],
    res:[["LangChain","docs","https://python.langchain.com/docs/"],["Instructor (structured outputs)","repo","https://github.com/jxnl/instructor"]],
    iq:["Why enforce structured outputs with a schema?","When is multi-agent worth the complexity?"] },

  { id:"guardrails", phase:"llm", title:"Guardrails, Safety & Structured Outputs", kind:"lesson", off:[300,-60], prereq:["llm-apps"], est:"2-3 hrs", badges:["standards"],
    goal:"Output validation, prompt-injection defense, and PII handling.",
    obj:["Validate and constrain model outputs.",
         "Defend against prompt injection and tool misuse.",
         "Handle PII and sensitive data responsibly."],
    ai:{ t:"Adversarial thinking", p:"Have an agent try to break your app with injections; you patch each hole it finds.",
         v:"Verify defenses by running an injection test suite and confirming each attack fails." },
    body:"Teach guardrails and safety for LLM apps: output validation, prompt-injection attacks and defenses, tool-use safety, and PII handling. Have me red-team my own app and add defenses that provably block the attacks.",
    dod:[["Added output validation and injection defenses","std"],["Red-teamed the app and closed the holes",null]],
    res:[["OWASP LLM Top 10","article","https://owasp.org/www-project-top-10-for-large-language-model-applications/"]],
    iq:["How does prompt injection work and how do you defend against it?"] },

  { id:"llmops", phase:"llm", title:"LLMOps in Production", kind:"lesson", off:[300,80], prereq:["llm-apps","mlops"], est:"3-4 hrs", badges:["emerging","standards"],
    goal:"Prompt/version management, observability (Langfuse/LangSmith), caching, model routing, and cost/latency.",
    obj:["Instrument an LLM app with tracing and observability.",
         "Cache and route between models to control cost and latency.",
         "Manage prompt versions and roll back safely."],
    ai:{ t:"Operate the AI", p:"Production LLM systems need the same rigor as any service: tracing, cost control, and safe rollout.",
         v:"Verify observability by tracing a real request end to end, including token cost and latency." },
    body:"Teach LLMOps: tracing and observability with Langfuse or LangSmith, caching, model routing to balance cost and quality, prompt version management, and latency/cost optimization. Have me instrument my LLM app and cut its cost or latency measurably.",
    dod:[["Instrumented the app with tracing/observability","std"],["Reduced cost or latency and measured it",null]],
    res:[["Langfuse","docs","https://langfuse.com/docs"]],
    iq:["What do you monitor for an LLM app in production?","How does model routing save cost?"] },

  { id:"mcp-server", phase:"llm", title:"Build an MCP Server + GenAI Data Pipelines", kind:"lesson", off:[70,130], prereq:["mcp-agents","rag","dlt"], est:"4-5 hrs", badges:["emerging","ai"],
    goal:"Serve your data to agents via MCP; ingest and prepare unstructured data at scale for RAG.",
    obj:["Build your own MCP server exposing your data and tools to agents.",
         "Build a pipeline that prepares messy unstructured data for RAG.",
         "See why DE-for-AI is a rare, high-value skill."],
    ai:{ t:"You build the AI infrastructure", p:"This is the DE-for-AI angle: the person who can pipe clean, current data into agents and RAG systems is who AI teams cannot hire fast enough.",
         v:"Verify the server and pipeline with a real agent querying live, correctly-prepared data." },
    body:"Teach me to build my own MCP server that exposes my data and tools to agents, and a data pipeline that ingests and prepares unstructured data (documents, transcripts, web) at scale for RAG: cleaning, chunking, embedding, and refreshing. Have me connect Claude or another agent to my server.",
    dod:[["Built and connected my own MCP server",null],["Built an unstructured-data pipeline feeding RAG",null]],
    res:[["MCP","docs","https://modelcontextprotocol.io/"]],
    iq:["Why is preparing unstructured data the hard part of production RAG?","What would you expose through an MCP server and what would you not?"] },

  { id:"m7", phase:"llm", title:"Milestone 7 · AI Product on Your Data", kind:"project", off:[300,170], prereq:["rag","eval-llm","mcp-server"], est:"18-24 hrs", badges:["emerging","ai","standards"],
    goal:"An advanced AI product on your own data, with a real eval harness - a standalone portfolio repo.",
    obj:["Ship an AI product on data you care about.",
         "Prove quality with an eval harness and guardrails.",
         "Package it as a production-ready, portfolio-worthy repository."],
    ai:{ t:"Prove it is good", p:"Anyone can demo an LLM; you ship one with evals, guardrails, and observability that a team could actually run.",
         v:"Verify with your eval harness on every change, and show how you would catch it degrading over time." },
    body:"Coach me to build an advanced AI product on my own data, with retrieval, guardrails, observability, and a real eval harness. Enforce the portfolio-repo rules: README with architecture and an eval writeup (how I proved it is good and how I would catch degradation), atomic conventional commits, LICENSE, no emojis, and no references to any AI tool or to this course.",
    dod:[["Working AI product on my own data",null],["Eval harness proving quality; guardrails in place","std"],["README with architecture and eval writeup","std"],["Standalone repo, atomic commits; no AI/course references","std"]],
    res:[["ragas","docs","https://docs.ragas.io/"]],
    iq:["How did you prove your AI system is actually good?","How would you detect it degrading in production?"],
    options:[
      { th:"productivity", tt:"RAG over your knowledge base", p:"A grounded assistant over your notes/documents, with citations and an eval set." },
      { th:"finance", tt:"Chat with your finances", p:"An LLM interface over your transaction data that answers questions and never fabricates numbers." },
      { th:"cs / automation", tt:"MCP server over your data", p:"Expose a personal dataset to Claude/agents via your own MCP server, with guardrails." } ] },

  /* ---------- 9 · Capstone & Getting Hired ---------- */
  { id:"capstone", phase:"cap", title:"The Capstone", kind:"capstone", off:[-120,-10], prereq:["m5","m6","m7"], est:"40-60 hrs", badges:["standards"],
    goal:"One end-to-end platform fusing ingestion, lakehouse, warehouse, transform, streaming, and an AI feature.",
    obj:["Fuse the milestones into one coherent platform.",
         "Document it with architecture diagrams and decision records.",
         "Make it the signature project on your resume."],
    ai:{ t:"Your flagship", p:"Combine everything: dlt ingestion, S3/Iceberg lake, warehouse, dbt/SQLMesh, orchestration, a streaming feed, and an AI/RAG feature, with CI, IaC, and observability.",
         v:"Verify the whole platform runs end to end from a clean clone, following only the README." },
    body:"Coach me to build the capstone: a single, coherent, end-to-end data-and-AI platform that combines the earlier milestones, with CI, IaC, and observability, documented with architecture diagrams and a couple of ADRs. Enforce the portfolio-repo rules at the highest bar. This is the project I lead interviews with.",
    dod:[["End-to-end platform runs from a clean clone via the README",null],["Architecture diagrams and ADRs","std"],["CI, IaC, observability all present","std"],["Flagship-quality repo; no AI/course references anywhere","std"]],
    res:[["C4 model (architecture)","article","https://c4model.com/"],["ADR","repo","https://github.com/joelparkerhenderson/architecture-decision-record"]],
    iq:["Present your capstone as a 10-minute system design.","What are its top three limitations and how would you fix them?"],
    options:[
      { th:"your theme", tt:"Unify your milestones", p:"Combine your favorite milestones into one platform on a theme you care about, end to end." } ] },

  { id:"portfolio", phase:"cap", title:"Portfolio & GitHub Craft", kind:"lesson", off:[30,-110], prereq:["m5"], est:"3-4 hrs", badges:["standards"],
    goal:"READMEs, architecture diagrams, writeups, and making repos legible in 60 seconds.",
    obj:["Write a README that sells a project in 60 seconds.",
         "Produce clean architecture diagrams and a short writeup or blog post.",
         "Audit every repo against the portfolio-repo rules."],
    ai:{ t:"Draft, then sharpen", p:"Use an agent to draft READMEs and diagrams; you cut fluff and ensure zero AI/course references remain.",
         v:"Verify each repo passes a hiring-manager skim and contains no emojis or tool/course references." },
    body:"Teach me to make my repos hireable: a crisp README structure, architecture diagrams, a results section, and a short writeup or blog post per project. Audit each of my project repos against the portfolio-repo rules and fix anything that leaks the course or an AI tool.",
    dod:[["Every project repo has a 60-second README and a diagram","std"],["All repos audited: no emojis, no AI/course references","std"]],
    res:[["Make a README","article","https://www.makeareadme.com/"]],
    iq:["What does a hiring manager look for in the first 60 seconds of a repo?"] },

  { id:"sysdesign", phase:"cap", title:"System Design for Data & AI", kind:"lesson", off:[110,60], prereq:["capstone"], est:"4-5 hrs",
    goal:"Designing pipelines, platforms, and RAG systems in interviews: tradeoffs and sizing.",
    obj:["Structure a data/AI system-design answer under time pressure.",
         "Reason about tradeoffs and do back-of-envelope sizing.",
         "Design a RAG or streaming system on a whiteboard."],
    ai:{ t:"Mock interviewer", p:"Have an agent run system-design mocks and grade you against a rubric; you close the gaps.",
         v:"Verify improvement by re-doing a prompt cold and comparing to the rubric." },
    body:"Teach data and AI system design for interviews: a repeatable structure, tradeoffs, sizing, and worked examples (a batch platform, a streaming pipeline, a RAG system). Run mock questions and grade my answers against a rubric.",
    dod:[["Answered three system-design prompts against a rubric",null],["Can size a pipeline back-of-envelope",null]],
    res:[["System design primer","repo","https://github.com/donnemartin/system-design-primer"]],
    iq:["Design a pipeline ingesting 1TB/day for analytics.","Design a production RAG system for 10M documents."] },

  { id:"interview", phase:"cap", title:"Interview Prep", kind:"lesson", off:[240,-40], prereq:["sysdesign"], est:"ongoing", badges:["standards"],
    goal:"SQL gauntlet, Python/data challenges, take-homes, ML/LLM rounds, and behavioral stories.",
    obj:["Drill SQL and Python/data challenges to fluency.",
         "Prepare take-home and ML/LLM system-design rounds.",
         "Build behavioral stories from your real projects."],
    ai:{ t:"Endless practice partner", p:"Use an agent to generate and grade SQL/Python drills and to mock behavioral rounds against your projects.",
         v:"Verify by solving cold, timed, without AI, then reviewing with it." },
    body:"Run me through interview prep: a SQL drilling gauntlet, Python/data challenges, take-home strategy, ML/LLM system-design rounds, and behavioral stories grounded in my portfolio. Quiz me hard, time me, and review like an interviewer.",
    dod:[["Fluent on a bank of SQL and Python challenges",null],["Behavioral stories prepared from my real projects",null]],
    res:[["DataLemur (SQL)","article","https://datalemur.com/"],["LeetCode","article","https://leetcode.com/"]],
    iq:["Tell me about a data pipeline you built and a hard tradeoff you made."] },

  { id:"jobhunt", phase:"cap", title:"Positioning & Job Hunt", kind:"lesson", off:[240,110], prereq:["portfolio","interview"], est:"ongoing", badges:["standards"],
    goal:"Resume, LinkedIn, DE vs AI-leaning targeting, and the narrative threading your projects.",
    obj:["Write a resume and LinkedIn that pass the six-second scan.",
         "Target DE vs AI-leaning roles deliberately.",
         "Tell one coherent story that ties your projects together."],
    ai:{ t:"Tailor and sharpen", p:"Use an agent to tailor your resume per role and to pressure-test your narrative; you keep it truthful and specific.",
         v:"Verify with real signal: track application-to-response rate and iterate." },
    body:"Coach me on positioning and the job hunt: a strong resume and LinkedIn, choosing DE vs AI-leaning targets, and a narrative that threads my capstone and milestones into one story. Help me tailor applications and prepare for outreach.",
    dod:[["Resume and LinkedIn that pass a six-second scan","std"],["A clear DE-vs-AI targeting plan and project narrative",null]],
    res:[["Tech resume advice","article","https://www.levels.fyi/blog/"]],
    iq:["Why do you want to be a data engineer, and why now?"] }
];
